version: '3'

services:
  postgres:
    container_name: betterbudget_postgres
    restart: always
    logging:
      driver: "syslog"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=betterbudget
      - POSTGRES_DB=betterbudget
  mongo:
    container_name: betterbudget_mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: api
    build: .
    restart: always
    command: yarn dev:server
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - mongo
